apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app: metrics-server
    environment: all
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.12.2
      chart: metrics-server
      helm:
        valueFiles:
          - $values/platforms/metrics-server/values.yaml
    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "apiregistration.k8s.io"
      kind: "APIService"
      name: "v1beta1.metrics.k8s.io"
      jsonPointers:
        - /spec/insecureSkipTLSVerify
