apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-secret
spec:
  refreshInterval: 24h # SecretStoreプロバイダーから再度値を読み込む時間を指定
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: openai-secret
    creationPolicy: Owner
  data: # 取得する秘匿情報を指定する
    - secretKey: api-key
      remoteRef:
        key: translate-prod-openai-api-key
        property: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: translate-service
  labels:
    auth: required
    app: translate
spec:
  type: ClusterIP
  selector:
    app: translate
  ports:
    - name: http-translate
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwks-url
data:
  url: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI/.well-known/jwks.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  selector:
    matchLabels:
      app: translate
  template:
    metadata:
      labels:
        env: prod
        app: translate
    spec:
      containers:
        - name: translate
          env:
            - name: JWT_AUTH_FLAG
              value: "true"
            - name: JWKS_URL
              valueFrom:
                configMapKeyRef:
                  name: jwks-url
                  key: url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key

            - name: FRONTEND_HOST
              value: "*"
          image: ___IMAGE_URL___@___IMAGE_DIGEST___
          ports:
            - containerPort: 8080
