apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ele-route-backend
spec:
  hostnames:
    - "dev.kaiandkai.com"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ele-route-frontend
spec:
  hostnames:
    - "dev.www.kaiandkai.com"
