apiVersion: v1
kind: Namespace
metadata:
  name: in-house
  labels:
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
    gateway-api: default
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    #istio-injection: enabled
    gateway-api: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: stg
  labels:
    name: stg
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    istio-injection: enabled
    gateway-api: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    name: falco
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    name: istio-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    name: kiail-operator
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    #istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    #istio-injection: enabled
