apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: cert-manager
    environment: all
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.16.3
      chart: jetstack/cert-manager
      helm:
        valueFiles:
          - $values/platforms/cert-manager/values.yaml

    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
