apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-backend-gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-frontend-gateway
