apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    app: loki
    environment: all
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.0
    chart: loki
    helm:
      values: |
        global:
          extraEnvFrom:
            - secretRef:
                name: loki-aws-credentials
        deploymentMode: SingleBinary
        loki:
          commonConfig:
            replication_factor: 1
          auth_enabled: false
          tracing:
            enabled: true
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                index:
                  prefix: loki_index_
                  period: 24h
                object_store: s3
                schema: v13

          storage:
            type: "s3"
            bucketNames:
              chunks: "kai-loki-backend-admin-bucket"
              ruler: "kai-loki-backend-index-bucket"
              admin: "kai-loki-backend-admin-bucket"
            s3:
              region: "ap-northeast-1"
              accessKeyId: ${AWS_ACCESS_KEY_ID}
              secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

        chunksCache:
          allocatedMemory: 500
          singleBinary:
            replicas: 1
            extraArgs:
              - "--config.expand-env=true"
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-aws-credentials
                  key: aws_secret_access_key

        singleBinary:
          replicas:  1
          extraArgs:
            - "--config.expand-env=true"
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-aws-credentials
                  key: aws_secret_access_key


        backend:
          affinity:{}
        write:
          affinity:{}
        read:
          affinity:{}
        minio:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
