apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-app
  namespace: argocd
  labels:
    app: external-secrets
    environment: all
spec:
  project: default
  source:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.13.0
      helm:
        valueFiles:
          - $values/platforms/external-secrets/values.yaml
    - repoURL: https://github.com/u-kai/k8s-in-home
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
