apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:e98da6457b974a6123de70344b4224f6ecccc399f0bd719f0dbee0ad42a16e46
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front
  newTag: 0179e8453c0c39fbaff6ecb48f2478038fde619b
