apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:c1dfdb7f3c60d37c072f0547d7e296dcac8505433c7f267a3c1c4cdebeb2983b
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:561f4eca509979f2d64eed46369e94832cdb487b
