apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:fe37dbb037121343985cd4e1fdea243616808dd6841178df2e3d6b0aa9a59a09
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/ele-front:a0637bd9bc12d33cb3eb8a488a20d866c4eb9858
