apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:34e76d8635da98ddfe219eb0872b2b50aea33d635d00327d2d2d281d3f12a480
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:6cf0d0f92318abfeca8d0d2cefbfc10307018286
