apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:3c613767f69c035360920cb00e3af31f1c87ae7c9d22dfc8da6e4ab9cb95a98e
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:faef461eadb9705c83efef4a2bd0422ee4e0e20b
