apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:c2e0422584d0d6179f83e3a9018949698214f75af0dba2e0057cdfef48982c1b
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front
  newTag: f8bc76575365a8eab051bb3eeb8ff195988af048
