apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:5583eb96387d38291f7cf0d0d4a32724410525a0ac9b1bb562c77047d2554eb1
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:92c3b52f439014007ea9c3de3bbb073704d071f4
