apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:4a94759407507aee1fafc4378aa50e00e57da8af271318b9d8b4c7bed6540226
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:8df0d243ee7eaa7e9a428f06919610fa209cd64c
