apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:964b79cd25d78b19c4e0b46ebc4974ca640fe43964c1f3f06c4fd85f8db2685f
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:4ef9c0e4738ffa083e7b5d01b6af1d4e643420d2
