apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:ac59593187eec770c72d357b409f3b9ba64ee6c5f31fefe56add0afb7fb102a0
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:cb1877f3ac3aa15bd54005515d2140923241d94d
