apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:9d387b750ef32210567828d6aa4f184545a2959e3036b4343c0ec4fc69c7c99f
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front
  newTag: f36332c58443d4f1792d8029c3e928020efd4d54
