apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:f5a5bd01dce433f11433f151a030c1684373554ecbb6b9ba4b7fcb89ecbbcf81
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/ele-front:087ceb9a2906ccda35d7506338f7c5a20b260b6b
