apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build-and-push-listener
  namespace: dev

spec:
  serviceAccountName: tekton-admin
  triggers:
    - name: translate-github-listener
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: github-secret
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - push
            - name: addChangedFiles
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              value: extensions.changed_files.matches('backend/translate') || extensions.changed_files.matches('backend/common')

      template:
        ref: build-and-push-trigger-template
      bindings:
        - ref: translate-build-and-push-trigger-binding

    - name: wordbook-github-listener
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: github-secret
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - push
            - name: addChangedFiles
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              value: extensions.changed_files.matches('backend/wordbook') || extensions.changed_files.matches('backend/common')
      template:
        ref: build-and-push-trigger-template
      bindings:
        - ref: wordbook-build-and-push-trigger-binding

    - name: front-github-listener
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: github-secret
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - push
            - name: addChangedFiles
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              value: extensions.changed_files.matches('frontend')
      template:
        ref: build-and-push-trigger-template
      bindings:
        - ref: front-build-and-push-trigger-binding
