apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: front-build-and-push-trigger-binding
  namespace: dev
spec:
  params:
    - name: service-name
      value: ele-front
    - name: git-user-name
      value: $(body.pusher.name)
    - name: git-user-email
      value: $(body.pusher.email)
    - name: image-name
      value: uk1012/ele-front:$(body.head_commit.id)
    - name: context
      value: ./home-k8s-app/frontend
    - name: docker-file
      value: /Dockerfile
    - name: cache-repo
      value: home-web-cache
