apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: wordbook-build-and-push-trigger-binding
spec:
  params:
    - name: github-app-subpath
      value: wordbook
    - name: github-manifest-subpath
      value: wordbook-manifest
    - name: service-name
      value: wordbook
    - name: git-user-name
      value: $(body.pusher.name)
    - name: git-user-email
      value: $(body.pusher.email)
    - name: image-name
      value: uk1012/wordbook:$(body.head_commit.id)
    - name: context
      value: ./home-k8s-app/backend
    - name: docker-file
      value: /wordbook/Dockerfile
    - name: cache-repo
      value: wordbook-cache
