apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-request-auth
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: ele-gateway
  jwtRules:
    - issuer: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI"
      jwksUri: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI/.well-known/jwks.json"

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jwt-auth-policy
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: ele-gateway
  action: ALLOW
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
