#deploymentMode: SimpleScalable
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 2
  auth_enabled: false
  tracing:
    enabled: true
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: s3
        schema: v13

  storage:
    type: "s3"
    bucketNames:
      chunks: "kai-loki-backend-chunks-bucket"
      ruler: "kai-loki-backend-index-bucket"
      admin: "kai-loki-backend-admin-bucket"
    s3:
      region: "ap-northeast-1"
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}

chunksCache:
  allocatedMemory: 500
  singleBinary:
    replicas: 2
    extraArgs:
      - "--config.expand-env=true"
    extraEnvFrom:
      - secretRef:
          name: loki-aws-credentials

singleBinary:
  replicas: 3
  extraArgs:
    - "--config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-aws-credentials

backend:
  replicas: 0
write:
  replicas: 0
read:
  replicas:
    0

    #backend:
    #  replicas: 1
    #  extraArgs:
    #    - "--config.expand-env=true"
    #  extraEnvFrom:
    #    - secretRef:
    #        name: loki-aws-credentials
    #read:
    #  replicas: 1
    #  extraArgs:
    #    - "--config.expand-env=true"
    #  extraEnvFrom:
    #    - secretRef:
    #        name: loki-aws-credentials
    #write:
    #  replicas: 1
    #  extraArgs:
    #    - "--config.expand-env=true"
    #  extraEnvFrom:
    #    - secretRef:
    #        name: loki-aws-credentials
minio:
  enabled: false
