apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
  namespace: argocd
  labels:
    app: ingress-nginx-controller
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.1
      chart: ingress-nginx
      helm:
        valueFiles:
          - $values/platforms/ingress/values.yaml

    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
