apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
  labels:
    app: jaeger-operator
    environment: all
spec:
  project: default
  sources:
    - repoURL: https://jaegertracing.github.io/helm-charts
      targetRevision: 2.57.0
      chart: jaeger-operator
      helm:
        valueFiles:
          - $values/platforms/jaeger/values.yaml
    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
