apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
spec:
  resources:
    limits:
      memory: 512Mi
  ingress:
    ingressClassName: nginx
    hosts:
      - jaeger.example.com
