apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: auth.yaml
  - path: front.yaml
  - path: translate.yaml
  - path: wordbook.yaml
resources:
  - ../../base
namespace: prod
