apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: wordbook
          env:
            - name: FRONTEND_HOST
              value: https://www.kaiandkai.com
          image: uk1012/wordbook:52117e524eef3e6516390f4fe541f40782a92939
