apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: stg
  labels:
    name: stg
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: prd
  labels:
    name: prd
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    name: kiail-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  labels:
    name: tekton-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines-resolvers
  labels:
    name: tekton-pipelines-resolvers
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-dashboard
  labels:
    name: tekton-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
