apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-gateway
spec:
  listeners:
    - name: frontend
      hostname: "dev.www.kaiandkai.com"
      port: 80
      protocol: HTTP

    - name: backend
      hostname: "dev.kaiandkai.com"
      port: 80
      protocol: HTTP
