apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.3.28
    path: /media/pi/ex-ssd/grafana
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 24h # SecretStoreプロバイダーから再度値を読み込む時間を指定
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: grafana-admin-password
    creationPolicy: Owner
  data: # 取得する秘匿情報を指定する
    - secretKey: user
      remoteRef:
        key: grafana-admin-password
        property: user
    - secretKey: password
      remoteRef:
        key: grafana-admin-password
        property: password

---
#apiVersion: apps/v1
#kind: Service
#metadata:
#  name: grafana
#  namespace: monitoring
#  labels:
#    app: grafana
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 3000
#  selector:
#    app: grafana
