apiVersion: v1
kind: Service
metadata:
  name: wordbook-service
  labels:
    app: wordbook
spec:
  type: ClusterIP
  selector:
    app: wordbook
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  selector:
    matchLabels:
      app: wordbook
  template:
    metadata:
      labels:
        app: wordbook
    spec:
      containers:
        - name: wordbook
          image: ___IMAGE_URL___@___IMAGE_DIGEST___
          ports:
            - containerPort: 8080
