apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ele-route
spec:
  parentRefs:
    - name: ele-gateway
      namespace: istio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: translate-service
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /wordbook
      backendRefs:
        - name: wordbook-service
          port: 80
