apiVersion: v1
kind: Service
metadata:
  name: translate-service
  labels:
    app: translate
spec:
  type: ClusterIP
  selector:
    app: translate
  ports:
    - name: http-translate
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  selector:
    matchLabels:
      app: translate
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
        - name: translate
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key

            - name: FRONTEND_HOST
              value: "*"
          image: ___IMAGE_URL___@___IMAGE_DIGEST___
          ports:
            - containerPort: 8080
