apiVersion: v1
kind: Service
metadata:
  name: translate-service
  labels:
    app: translate
spec:
  type: LoadBalancer
  selector:
    app: translate
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  selector:
    matchLabels:
      app: translate
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
        - name: translate
          image: ___IMAGE_URL___@___IMAGE_DIGEST___
          ports:
            - containerPort: 8080
