apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: wordbook-service-policy
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: translate-service-policy
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-strict
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-permissive
