apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.5.3
      chart: grafana
      helm:
        valueFiles:
          - $values/platforms/grafana/values.yaml

    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
