apiVersion: ext
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: grafana
spec:
  refreshInterval: 24h # SecretStoreプロバイダーから再度値を読み込む時間を指定
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: grafana-admin-password
    creationPolicy: Owner
  data:
    - remoteRef:
        key: grafana-admin-password
        property: user
      secretKey: user
    - remoteRef:
        key: grafana-admin-password
        property: password
      secretKey: password
