apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-app
  namespace: argocd
  labels:
    app: external-secrets
    environment: all
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.12.1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
