apiVersion: v1
kind: Service
metadata:
  name: trend-service
  labels:
    app: trend
spec:
  type: ClusterIP
  selector:
    app: trend
  ports:
    - name: http-trend
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-deployment
spec:
  selector:
    matchLabels:
      app: trend
  template:
    metadata:
      labels:
        app: trend
    spec:
      containers:
        - name: trend
          image: u-kai/trend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value: trend
            - name: FRONTEND_HOST
              value: "http://localhost:5173"
            - name: MYSQL_HOST
              value: trend-db-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trend-db-secret
                  key: password

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trend-db
spec:
  serviceName: trend-db-service
  selector:
    matchLabels:
      app: trend-db
  template:
    metadata:
      labels:
        app: trend-db
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trend-db-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: trend-db-pv
              mountPath: /var/lib/mysql
            - name: initdb-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb-script
          configMap:
            name: trend-initdb-config
            items:
              - key: init.sql
                path: init.sql
        - name: trend-db-pv
          persistentVolumeClaim:
            claimName: trend-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trend-initdb-config
data:
  init.sql: |
    CREATE DATABASE trend;
    USE trend;
    CREATE TABLE words (
        word_id VARCHAR(255) PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL,
        value VARCHAR(255) NOT NULL,
        meaning TEXT,
        pronunciation VARCHAR(255),
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL,
        miss_count INT,
        remarks TEXT,
        like_rates TEXT
    );
    CREATE TABLE sentences (
        sentence_id VARCHAR(255) PRIMARY KEY,
        word_id VARCHAR(255) NOT NULL,
        value TEXT NOT NULL,
        meaning TEXT,
        pronunciation VARCHAR(255),
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL,
        FOREIGN KEY (word_id) REFERENCES words(word_id)
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: trend

---
apiVersion: v1
kind: Service
metadata:
  name: trend-db-service
  labels:
    app: trend-db
spec:
  type: ClusterIP
  selector:
    app: trend-db
  ports:
    - name: tcp-trend-db
      port: 3306
      targetPort: 3306
      protocol: TCP
