apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    app: prometheus
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.24.0
      chart: prometheus
      helm:
        valueFiles:
          - $values/platforms/prometheus/values.yaml
    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
  labels:
    app: prometheus-blackbox-exporter
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.0.1
    chart: prometheus-blackbox-exporter
    helm:
      values: |
        config:
            modules:
              http_2xx:
                prober: http
                timeout: 5s
                http:
                  valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                  follow_redirects: true
                  preferred_ip_protocol: "ip4"

              ssh_banner:
                prober: tcp
                tcp:
                  query_response:
                    - expect: "^SSH-2.0-"
