apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: translate
          env:
            - name: FRONTEND_HOST
              value: https://www.kaiandkai.com
