apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:336a7d64f5750519d48d339d0175642cc2d0183b6cda084083339682edcd1ecc
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/ele-front:df6013dcccb856dbd37bf769b93083f7c2330342
