apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:e43407a17254447e57452053504c1c9daaf0932e29b6c3f4e1b8e216c2675c95
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/ele-front:27ae801ccbdc2a6a544ee81d351a91f4b3543fe1
