apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:a2ec8f99e86504948803e9b726b2d085f28854f5ecbe7fa24dede6fec56e9c6b
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/ele-front
    newTag: cd0d772259dc00569cd4042904e6226c3ddb5ee0
