apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:130176fade12531b9a2cfd3754b8eeb534bcd0f48e493fece4477464a5ef67e5
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/ele-front
    newTag: 09b40627f16029ef73fc9887416128699383664f
