apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-request-auth
spec:
  selector:
    matchLabels:
      service: ele
  jwtRules:
    - issuer: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI"
      jwksUri: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI/.well-known/jwks.json"
      forwardOriginalToken: true
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: wordbook-policy
spec:
  selector:
    matchLabels:
      app: wordbook
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            paths: ["/translate/health"]
            methods: ["GET"]
    - to:
        - operation:
            methods: ["OPTIONS"]
    - from:
        - source:
            namespaces: ["prod"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: wordbook-db-policy
spec:
  selector:
    matchLabels:
      app: wordbook-db
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            paths: ["/translate/health"]
            methods: ["GET"]
    - to:
        - operation:
            methods: ["OPTIONS"]
    - from:
        - source:
            namespaces: ["prod"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: translate-service-policy
spec:
  selector:
    matchLabels:
      app: translate
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            paths: ["/translate/health"]
            methods: ["GET"]
    - to:
        - operation:
            methods: ["OPTIONS"]
    - from:
        - source:
            namespaces: ["prod"]
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-strict
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-permissive
spec:
  selector:
    matchLabels:
      access: permissive
  mtls:
    mode: PERMISSIVE
