apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-front-prod
  namespace: argocd
  labels:
    app: ele-front
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/front/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: translate
  namespace: argocd
  labels:
    app: translate
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/translate/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordbook
  namespace: argocd
  labels:
    app: wordbook
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/wordbook/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-config
  namespace: argocd
  labels:
    app: ele-config
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/config/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            ## awssm-secretは別途手動で作成する
            name: awssm-secret
            key: key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-auth
  namespace: argocd
  labels:
    app: ele-auth
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/auth/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
