apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-prod
  namespace: argocd
  labels:
    app: ele-front
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            ## awssm-secretは別途手動で作成する
            name: awssm-secret
            key: key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret
