apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  labels:
    app: istiod
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks/0/failurePolicy
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.1
      chart: istiod
      helm:
        valueFiles:
          - $values/platforms/istio/values.yaml
    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
