meshConfig:
  tracing:
    sampling: 100
    zipkin:
      address: simplest-collector.observability.svc.cluster.local:9411
  defaultConfig:
    tracing: {}
  enableTracing: true
  extensionProviders:
    - name: jaeger
      opentelemetry:
        port: 4318
        service: simplest-collector.observability.svc.cluster.local
