apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  replicas: 3
  spec:
    containers:
      env:
        - name: FRONTEND_HOST
          value: https://www.kaiand.kai.com
