apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:72ad376fa2198f891dc061e9b55f256893d9e68297a9972059bc5d148d498c9d
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/wordbook
    newTag: 39554bc936c3318e4db7bebe72810ff0391d0f7f
