apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:63970723c55230d6da247a2bb690cbef4b2fa43d52a9c1cbf350240e9594a5c0
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/wordbook:533151b26b209f21bda1155ac0ba197a9fe6f0fc
