kind: PersistentVolume
apiVersion: v1
metadata:
  name: tekton
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tekton
  nfs:
    server: 192.168.3.26
    path: /mnt/share/nfs/tekton
