kind: PersistentVolume
apiVersion: v1
metadata:
  name: tekton
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tekton
  nfs:
    server: 192.168.3.28
    path:
      /media/pi/ex-ssd/tekton
      #path: /mnt/share/ex-ssd/tekton
