kind: PersistentVolume
apiVersion: v1
metadata:
  name: tekton-pv-app
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tekton
  nfs:
    server: 192.168.3.26
    path: /mnt/share/nfs/tekton
