apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-prod
  namespace: argocd
  labels:
    app: ele-front
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
# TODO dev
