apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-house
  namespace: argocd
  labels:
    app: in-house
spec:
  destination:
    namespace: in-house
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/in-house
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
