apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-frontend-gateway
  namespace: istio-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: prod
      hostname: "www.kaiandkai.com"
      port: 443
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: other
      hostname: "*.kaiandkai.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-backend-gateway
  namespace: istio-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: prod
      hostname: "api.kaiandkai.com"
      port: 443
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: other
      hostname: "*.kaiandkai.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: non-prod-gateway
      hostname: "*.kaiandkai.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
