apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-password
spec:
  refreshInterval: 24h # SecretStoreプロバイダーから再度値を読み込む時間を指定
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: mysql-password
    creationPolicy: Owner
  data: # 取得する秘匿情報を指定する
    - secretKey: password
      remoteRef:
        key: wordbook-db-password-stg
        property: password
---
apiVersion: v1
kind: Service
metadata:
  name: wordbook-service
  labels:
    app: wordbook
spec:
  type: LoadBalancer
  selector:
    app: wordbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  replicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordbook-pvc
spec:
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordbook-pvc
spec:
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordbook-db-service
  labels:
    app: wordbook-db
spec:
  type: LoadBalancer
  selector:
    app: wordbook-db
  ports:
    - name: tcp-wordbook-db
      port: 3306
      targetPort: 3306
      protocol: TCP
