apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  labels:
    app: cilium
    environment: all
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.15.0
    chart: cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    parameters:
