apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  labels:
    app: falco
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.11.1
    chart: falco
    helm:
      values: |
        falcosidekick:
          enabled: true
          config:
            existingSecret: slack-api-url
            slack:
              enabled: true
          webui:
            enabled: true
          prometheusRules:
            enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-resources
  namespace: argocd
  labels:
    app: falco-resources
    environment: all
spec:
  project: default
  source:
    path: argocd/apps/infra/resources/falco
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
