apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    environment: all
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.3
    chart: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    valueFiles:
      - values/grafana.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-resources
  namespace: argocd
  labels:
    app: grafana
    environment: all
spec:
  project: default
  source:
    path: argocd/apps/infra/resources/grafana
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 30
        factor: 2
        maxDuration: 300
