apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  labels:
    app: jaeger
    environment: all
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 3.3.1
    chart: jaeger
    helm:
      values: |
        cassandra:
          jvm:
            maxHeapSize: "1024MB"
            newHeapSize: "256MB"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
