apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  labels:
    app: kiali
    environment: all
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.89.0
    chart: kiali-operator
    helm:
      values: |
        cr:
          create: true
          name: kiali
          namespace: "istio-system"
          strategy: anonymous
          external_services:
              grafana:
                auth:
                  ca_file: ""
                  insecure_skip_verify: false
                  password: ""
                  token: ""
                  type: "none"
                  use_kiali_token: false
                  username: ""
                dashboards:
                - name: "Istio Service Dashboard"
                  variables:
                    namespace: "var-namespace"
                    service: "var-service"
                - name: "Istio Workload Dashboard"
                  variables:
                    namespace: "var-namespace"
                    workload: "var-workload"
                - name: "Istio Mesh Dashboard"
                - name: "Istio Control Plane Dashboard"
                - name: "Istio Performance Dashboard"
                - name: "Istio Wasm Extension Dashboard"
                enabled: true
                health_check_url: ""
                # default: in_cluster_url is undefined
                in_cluster_url: ""
                is_core: false
                url: "http://grafana.monitoring.svc.cluster.local:80"
              istio:
                component_status:
                  enabled: true
                config_map_name: "istio"
                egress_gateway_namespace: ""
                envoy_admin_local_port: 15000
                gateway_api_classes: []
                ingress_gateway_namespace: ""
                istio_api_enabled: true
                # default: istio_canary_revision is undefined
                istio_canary_revision:
                  current: "1-9-9"
                  upgrade: "1-10-2"
                istio_identity_domain: "svc.cluster.local"
                istio_injection_annotation: "sidecar.istio.io/inject"
                istio_sidecar_annotation: "sidecar.istio.io/status"
                istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
                istiod_deployment_name: "istiod"
                istiod_pod_monitoring_port: 15014
                root_namespace: ""
                url_service_version: ""
              prometheus:
                auth:
                  ca_file: ""
                  insecure_skip_verify: false
                  password: ""
                  token: ""
                  type: "none"
                  use_kiali_token: false
                  username: ""
                cache_duration: 10
                cache_enabled: true
                cache_expiration: 300
                # default: custom_headers is empty
                custom_headers:
                  customHeader1: "customHeader1Value"
                health_check_url: ""
                is_core: true
                # default: query_scope is empty
                query_scope:
                  mesh_id: "mesh-1"
                  cluster: "cluster-east"
                thanos_proxy:
                  enabled: false
                  retention_period: "7d"
                  scrape_interval: "30s"
                url: "http://prometheus-server.monitoring.svc.cluster.local:80"
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
