apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  labels:
    app: kiali
    environment: all
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.89.0
    chart: kiali-operator
    helm:
      values: |
        cr:
          create: true
          name: kiali
          namespace: "istio-system"
          strategy: anonymous
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
