apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo-es
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 24h # SecretStoreプロバイダーから再度値を読み込む時間を指定
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: github-repo-secret
    creationPolicy: Owner
  data: # 取得する秘匿情報を指定する
    - secretKey: type
      remoteRef:
        key: k8s-in-home-github-app-private-key
        property: type
    - secretKey: url
      remoteRef:
        key: k8s-in-home-github-app-private-key
        property: url
    - secretKey: githubAppID
      remoteRef:
        key: k8s-in-home-github-app-private-key
        property: githubAppID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: k8s-in-home-github-app-private-key
        property: githubAppInstallationID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: k8s-in-home-github-app-private-key
        property: privateKey
