apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:9e2c22a89083cb1208580ff956538a969bd8878207da5ae40a7b07e1f79e1f77
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate
  newTag: 52117e524eef3e6516390f4fe541f40782a92939
