apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:7d39bec60ab03dcd5c38baac8d83da2f3f79f466230118aa1c854f42685bef4f
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:43eaf9e4ab79b6360d62b6290a256c636297c6ad
