apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:34228893335bc20b8aebbad074ac1a08ec0cdeac721df2a1b31dcfd086103224
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:4e61ca86407d0dca5aaf0cc215a55e3588cfabcd
