apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:d36873e21c3e0aadc094e568ad092d5a6d5d392d3574fbdd3be5d60721d9f605
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:bce784d198196f9fdf256d9f2f46d1727ed5128c
