apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:2cbb4b21be41afdd1440af15133f9a270406a8f0c762805f9a15cc7f18c532cf
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate
  newTag: 24c75c2930e529c5fcbb8aab9a67238a7ce05eca
