apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:cc99b88079982bf7fccbdcc13ed67c61444193bef086605e5cc526e2a9dd1319
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:8413ed50c6c782eb575cfc44360ad5831092823f
