apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:d7673f6bad0131cbfb6f8361693d8ebad8e06e50b17ad7bdf3b42b75830045c0
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:05bfdcdc2f505e115a2da08c816c627b44ba7a87
