apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:9ebb5b28fd64f3650f667fe6e70dc193ba1ddd30da9a13387026d5dfd2ed9cfc
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/translate:533151b26b209f21bda1155ac0ba197a9fe6f0fc
