kind: PersistentVolume
apiVersion: v1
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.3.28
    path: /media/pi/ex-ssd/loki
