apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:4ed05aa82a47e7f7ba9e1773d90ef39084e32baf23f9e6dd2b6271d244259e44
  name: __IMAGE_URL__@__IMAGE_DIGEST__
  newName: uk1012/home-web:7688904af2fbf584aa51ab7578b681ad90c25e8b
