apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "*.kaiandkai.com"
      port: 80
      protocol: HTTP
