apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: frontend
      hostname: "www.kaiandkai.com"
      port: 443
      protocol: HTTPS

    - name: backend
      hostname: "api.kaiandkai.com"
      port: 443
      protocol: HTTPS
