apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-backend-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: backend
      hostname: "api.kaiandkai.com"
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ele-frontend-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: frontend
      hostname: "www.kaiandkai.com"
      port: 80
      protocol: HTTP
