apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-request-auth
spec:
  targetRefs:
    - name: ele-backend-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  jwtRules:
    - issuer: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI"
      jwksUri: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OlP3TVnbI/.well-known/jwks.json"
      forwardOriginalToken: true

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jwt-auth-policy-allow-options
spec:
  targetRefs:
    - name: ele-backend-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["OPTIONS"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jwt-auth-policy-allow-requests
spec:
  targetRefs:
    - name: ele-backend-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            notPaths: ["/wordbook/health"]
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-strict
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-permissive
spec:
  selector:
    matchLabels:
      access: permissive
  mtls:
    mode: PERMISSIVE
