apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordbook-db-pv-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wordbook-dev
  hostPath:
    path: /media/pi/ex-ssd/wordbook-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordbook-db-pv-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wordbook-test
  hostPath:
    path: /media/pi/ex-ssd/wordbook-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordbook-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wordbook
  hostPath:
    path: /media/pi/ex-ssd/wordbook
