apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:68e36b7f1788dc461b58041c6f377dadcfd19c0fa0349f63bc0341b056b038d5
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/translate
    newTag: 5cc1ff404018fbc6ebeb1997e89090d2c9a804ee
