apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:8cd13583e11abfc89c88dd2df4a04ddbdede72da6f6638131a336da35e42d73f
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/translate
    newTag: 8fe7dff6881242fb64f194cf4d09121c252d6576
