apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:6f2504a09b07d395ba6d5886f5da8bac0e19979a9faacaa547818cb70186bd20
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/translate:08a7777aa734ada450649d62284fd083f47623df
