apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
images:
  - digest: sha256:7925893b516044d5f40a0fc0e9aefb5db073f64ba0f0376915d92b162ff54ed9
    name: ___IMAGE_URL___@___IMAGE_DIGEST___
    newName: uk1012/translate
    newTag: d18ac64d920ba4cb6bc29ca993801879afdfc14a
