apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  labels:
    app: falco
    environment: all
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      targetRevision: 4.11.1
      chart: falco
      helm:
        valueFiles:
          - $values/platforms/falco/values.yaml

    - repoURL: https://github.com/u-kai/k8s-in-home.git
      targetRevision: main
      ref: values
