apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatewayapi-crd-install
  namespace: argocd
  labels:
    app: gateway
    environment: all
spec:
  project: default
  source:
    kustomize:
    repoURL: https://github.com/u-kai/k8s-in-home.git
    path: gatewayapi/crd-install
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
