apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ele-backend-route
spec:
  hostnames:
    - "api.kaiandkai.com"
  parentRefs:
    - name: ele-backend-gateway
      namespace: istio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /wordbook
      backendRefs:
        - name: wordbook-service
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /translate
      backendRefs:
        - name: translate-service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ele-frontend-route
spec:
  hostnames:
    - "www.kaiandkai.com"
  parentRefs:
    - name: ele-frontend-gateway
      namespace: istio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ele-front-service
          port: 80
