apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordbook
  template:
    metadata:
      labels:
        app: wordbook
    spec:
      containers:
        - name: wordbook
          env:
            - name: FRONTEND_HOST
              value: "http://www.dev.kaiandkai.com"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordbook-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: wordbook-dev
---
apiVersion: v1
kind: Service
metadata:
  name: wordbook-db-service
spec:
  selector:
    app: wordbook-db
  clusterIP: None
