apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordbook-deployment
spec:
  replicas: 1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordbook-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: wordbook-dev
