apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:dbb7197d1fd6b509bbe253c09a3da0777aad07927c099151379c37a5c658631b
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook:43eaf9e4ab79b6360d62b6290a256c636297c6ad
