apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:087f9346cbb435de00270f6cc4a28ebdba218b5084ff0fc5c4c591651662cc0d
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook:bce784d198196f9fdf256d9f2f46d1727ed5128c
