apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:ec1df0ce01ada646b8b5866528cb3612df934462fc923c83b958ba3bad124100
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook
  newTag: 9c27585a33656d4658964416efb195fd16098959
