apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:fc95de5dd19b1f55821eb412fe9f5814c5736c6acc860b0b94e02442a8b0b09c
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook:4e61ca86407d0dca5aaf0cc215a55e3588cfabcd
