apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:c7ac4ff9bafb3ac31a0b9d05d2faf03dd244a986481faf97d2537aee0ad2fb42
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook:e71ff1d4bd78e3b61655901c1f8adf52d79af706
