apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- digest: sha256:ac601db003d4d0cff7be4ce1a1e96a3e03c8033dfb895ea4a5b6afd84e4a0320
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: uk1012/wordbook:973886a6795b4fab4e2995c4df86564f4e66082b
