apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app-of-app
  namespace: argocd
  labels:
    app: cert-manager
    environment: all
spec:
  project: default
  source:
    repoURL: https://github.com/u-kai/k8s-in-home.git
    path: platforms/cert-manager
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
