apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-app-of-app
  namespace: argocd
  labels:
    app: ns
    environment: all
spec:
  project: default
  source:
    repoURL: https://github.com/u-kai/k8s-in-home.git
    path: platforms/namespaces
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
