apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-front-prod
  namespace: argocd
  labels:
    app: ele-front
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/front/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: translate
  namespace: argocd
  labels:
    app: translate
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/translate/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordbook
  namespace: argocd
  labels:
    app: wordbook
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/wordbook/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-config
  namespace: argocd
  labels:
    app: ele-config
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/config/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
