apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ele-router
  namespace: argocd
  labels:
    app: ele-router
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: services/ele/router/overlays/prod
    repoURL: https://github.com/u-kai/k8s-in-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
