apiVersion: v1
kind: Service
metadata:
  name: ele-front-service
  labels:
    app: ele-front
spec:
  type: ClusterIP
  selector:
    app: ele-front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ele-front-deployment
spec:
  selector:
    matchLabels:
      app: ele-front
  template:
    metadata:
      labels:
        app: ele-front
    spec:
      containers:
        - name: ele-front
          image: ___IMAGE_URL___@___IMAGE_DIGEST___
          ports:
            - containerPort: 80
